version: '3.8'
services:
  go:
    image: golang:1.16.5-buster
    tty: true
    stdin_open: true
    volumes:
      - ./sample-api:/go/src/work
    working_dir: /go/src/work
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PORT
      - MYSQL_HOST

  db:
    image: mysql:5.7.31
    environment:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./tmp/config:/etc/mysql/conf.d

  mongo-db:
    image: mongo:4.0.0
    container_name: mongo_db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27017:27017

volumes:
  dbdata:
    driver: local
